### ISSUE TITLE
Missing hostname and rewriteDomain parameter

### ISSUE THREAD

**Issue by brechsteiner** [thbe/puppet-ssmtp#11]
the module should have the parameter for hostname and rewriteDomain

**Comment by thbe** [comment]
Parameters added ...

**Comment by brechsteiner** [comment]
cool, thanks for fast reaction

**Comment by brechsteiner** [comment]
the parameters are missing in config.pp

**Comment by thbe** [comment]
Forgot the local variable scoping for that module, fixed as well
