### ISSUE TITLE
Yum Requirement?

### ISSUE THREAD

**Issue by mentalblock** [thbe/puppet-ssmtp#5]
I do not use a yum class. Is this absolutely necessary?

https://github.com/thbe/puppet-ssmtp/blob/master/manifests/init.pp#L44

**Comment by thbe** [comment]
No it is not necessary. The reason for the requirement is simple, ssmtp is not in the default repositories, you need to have EPEL enabled. Therefor, to satisfy automatic build dependencies, I've added the yum requirement to setup EPEL before testing the ssmtp module.
